name: Moodle Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Specify the directory to deploy (mod or themes)"
        required: true
        default: "mod"

jobs:
  fetch-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Deploy Target
        run: |
          # Read the deploy target from inputs
          DEPLOY_TARGET="${{ github.event.inputs.deploy_target }}"
          echo "Deploying target: $DEPLOY_TARGET"
          echo "DEPLOY_TARGET=$DEPLOY_TARGET" >> $GITHUB_ENV

      - name: Zip selected directory
        run: |
          # Zip the selected directory
          zip -r "${DEPLOY_TARGET}.zip" "./$DEPLOY_TARGET"
          echo "ZIP_PATH=$(pwd)/${DEPLOY_TARGET}.zip" >> $GITHUB_ENV

      - name: Backup current directory
        run: |
          # Create a timestamp for the backup
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          BACKUP_PATH="/tmp/${DEPLOY_TARGET}_backup_$TIMESTAMP.zip"

          # Backup the current target directory
          sudo zip -r "$BACKUP_PATH" "/var/www/html/moodle/$DEPLOY_TARGET"
          echo "Backup created at $BACKUP_PATH"

      - name: Deploy selected directory
        run: |
          # Deploy the selected directory
          sudo unzip -o ${{ env.ZIP_PATH }} -d "/var/www/html/moodle/"
          echo "Deployed the new $DEPLOY_TARGET directory"
