name: Moodle Deployment

on:
  push:
    branches:
      - main

jobs:
  fetch-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip mod directory
        run: |
          # Zip the `mod` directory
          zip -r mod.zip ./mod
          # Set the zip file path as an environment variable to use in the deploy job
          echo "MOD_ZIP_PATH=./mod.zip" >> $GITHUB_ENV

  deploy:
    runs-on: self-hosted
    needs: fetch-and-build

    steps:
      - name: Checkout repository on self-hosted runner
        uses: actions/checkout@v2

      - name: Backup current mod directory
        run: |
          # Backup the current `mod` directory to `/tmp`
          mv /var/www/html/moodle/mod /tmp/mod_backup
          echo "Backup created at /tmp/mod_backup"

      - name: Deploy new mod directory
        run: |
          # Extract the zip file into the mod directory
          unzip ${{env.MOD_ZIP_PATH}} -d /var/www/html/moodle/
          echo "Deployed the new mod directory"
