name: Moodle Deployment

on:
  push:
    branches:
      - main

jobs:
  fetch-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip mod directory
        run: |
          # Zip the `mod` directory
          zip -r mod.zip ./mod
          # Set the zip file path as an environment variable
          echo "MOD_ZIP_PATH=$(pwd)/mod.zip" >> $GITHUB_ENV

      - name: Backup current mod directory
        run: |
          # Backup the current `mod` directory to `/tmp`
          sudo mv /var/www/html/moodle/mod /tmp/mod_backup
          echo "Backup created at /tmp/mod_backup"

      - name: Deploy new mod directory
        run: |
          # Extract the zip file into the Moodle directory
          sudo unzip -o ${{ env.MOD_ZIP_PATH }} -d /var/www/html/moodle/
          echo "Deployed the new mod directory"
