name: Moodle Plugin Deployment Workflow

on:
  workflow_dispatch: # Enables manual trigger

jobs:
  deploy:
    name: Deploy Moodle Plugin
    runs-on: self-hosted

    env:
      MOODLE_SERVER_PATH: /var/www/html/moodle/mod/ # Moodle plugins directory

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Step 2: Detect changed directories under /mod
      - name: Detect Changed Directories
        id: detect_changes
        run: |
          CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | grep '^mod/' | cut -d '/' -f2 | sort | uniq)
          echo "Changed directories: $CHANGED_DIRS"
          echo "::set-output name=changed_dirs::$CHANGED_DIRS"

      # Step 4: Create ZIP Artifacts for changed directories
      - name: Create ZIP Artifacts
        run: |
          mkdir -p /home/ubuntu/artifact
          for DIR in ${{ needs.detect_changes.outputs.changed_dirs }}; do
            cd mod/$DIR
            zip -r /home/ubuntu/artifact/${DIR}.zip ./*
            cd ../../
            echo "Created artifact: /home/ubuntu/artifact/${DIR}.zip"
          done

      # Step 5: Backup Existing Directories on the Moodle server
      - name: Backup Existing Directories
        run: |
          for DIR in ${{ needs.detect_changes.outputs.changed_dirs }}; do
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            sudo zip -r /tmp/${DIR}_backup_${TIMESTAMP}.zip ${{ env.MOODLE_SERVER_PATH }}${DIR}/
            echo "Backup created: /tmp/${DIR}_backup_${TIMESTAMP}.zip"
          done

      # Step 6: Deploy the Plugin ZIPs to Moodle server
      - name: Deploy Plugin
        run: |
          for DIR in ${{ needs.detect_changes.outputs.changed_dirs }}; do
            scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa /home/ubuntu/artifact/${DIR}.zip ubuntu@${{ env.MOODLE_SERVER_PRIVATE_IP }}:/home/ubuntu/
            echo "Plugin ZIP uploaded to Moodle server."
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ env.MOODLE_SERVER_PRIVATE_IP }} << EOF
              sudo unzip -o /home/ubuntu/${DIR}.zip -d /var/www/html/moodle/mod/
              sudo chown -R www-data:www-data /var/www/html/moodle/mod/
              sudo chmod -R 755 /var/www/html/moodle/mod/
              sudo -u www-data /usr/bin/php /var/www/html/moodle/admin/cli/upgrade.php --non-interactive
            EOF
            echo "Plugin deployed and Moodle upgraded successfully."
          done